name: .NET CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore MusicKeys/MusicKeys.csproj
      - name: Build
        run: dotnet build MusicKeys/MusicKeys.csproj -c Release --no-restore
      - name: Pack
        run: dotnet pack MusicKeys/MusicKeys.csproj -c Release -o out
